"""add_specialty_to_user_model

Revision ID: 184aa0212ad3
Revises: ce527c91edc4
Create Date: 2025-06-21 18:55:06.471304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '184aa0212ad3'
down_revision = 'ce527c91edc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_users_specialty_id', 'specialties', ['specialty_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_specialty_id', type_='foreignkey')
        batch_op.drop_column('specialty_id')

    # ### end Alembic commands ###
