"""add_payment_history_and_paid_amount_to_invoices

Revision ID: 2bf75da6dc39
Revises: 8ff2ffe90c25
Create Date: 2025-07-05 16:00:21.963606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf75da6dc39'
down_revision = '8ff2ffe90c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('transaction_reference', sa.String(length=100), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=False))

    with op.batch_alter_table('triages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feeding_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sleep_pattern', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('irritability', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fontanel', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('psychomotor_development', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('social_behavior', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('toilet_training', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('school_performance', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('physical_activity', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('mood_state', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('pubertal_development', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('menstruation_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('risk_behaviors', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('triages', schema=None) as batch_op:
        batch_op.drop_column('risk_behaviors')
        batch_op.drop_column('menstruation_status')
        batch_op.drop_column('pubertal_development')
        batch_op.drop_column('mood_state')
        batch_op.drop_column('physical_activity')
        batch_op.drop_column('school_performance')
        batch_op.drop_column('toilet_training')
        batch_op.drop_column('social_behavior')
        batch_op.drop_column('psychomotor_development')
        batch_op.drop_column('fontanel')
        batch_op.drop_column('irritability')
        batch_op.drop_column('sleep_pattern')
        batch_op.drop_column('feeding_status')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('paid_amount')

    op.drop_table('payment_history')
    # ### end Alembic commands ###
