"""restore date fields to work_schedule and remove from user

Revision ID: 526cbc82b6e5
Revises: 9f18f17f2edc
Create Date: 2025-07-05 20:32:11.360536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526cbc82b6e5'
down_revision = '9f18f17f2edc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('schedule_validity_date')

    with op.batch_alter_table('work_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_schedules', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_validity_date', sa.DATE(), nullable=True))

    # ### end Alembic commands ###
