"""add_adult_elder_fields_to_triage

Revision ID: 6a5454bf7342
Revises: 526cbc82b6e5
Create Date: 2025-07-07 11:01:00.698090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a5454bf7342'
down_revision = '526cbc82b6e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_histories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_histories_history_number'))

    op.drop_table('medical_histories')
    with op.batch_alter_table('triages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobility_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cognitive_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fall_risk', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('functional_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('chronic_conditions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('medication_polypharmacy', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('triages', schema=None) as batch_op:
        batch_op.drop_column('medication_polypharmacy')
        batch_op.drop_column('chronic_conditions')
        batch_op.drop_column('functional_status')
        batch_op.drop_column('fall_risk')
        batch_op.drop_column('cognitive_status')
        batch_op.drop_column('mobility_status')

    op.create_table('medical_histories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('history_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('opening_date', sa.DATE(), nullable=False),
    sa.Column('patient_id', sa.INTEGER(), nullable=False),
    sa.Column('personal_history', sa.TEXT(), nullable=True),
    sa.Column('family_history', sa.TEXT(), nullable=True),
    sa.Column('smoking_habits', sa.VARCHAR(length=50), nullable=True),
    sa.Column('alcohol_consumption', sa.VARCHAR(length=50), nullable=True),
    sa.Column('drug_use', sa.VARCHAR(length=50), nullable=True),
    sa.Column('physical_activity', sa.VARCHAR(length=100), nullable=True),
    sa.Column('other_habits', sa.TEXT(), nullable=True),
    sa.Column('known_allergies', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_histories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_histories_history_number'), ['history_number'], unique=1)

    # ### end Alembic commands ###
