"""add_blood_type_to_triage

Revision ID: 8ff2ffe90c25
Revises: 12e0a6b008d6
Create Date: 2025-07-04 12:13:43.134539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ff2ffe90c25'
down_revision = '12e0a6b008d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('triages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blood_type', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('triages', schema=None) as batch_op:
        batch_op.drop_column('blood_type')

    # ### end Alembic commands ###
