"""add schedule_validity_date to user and remove date fields from work_schedule

Revision ID: 9f18f17f2edc
Revises: 6f5c16021161
Create Date: 2025-07-05 20:22:31.601909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f18f17f2edc'
down_revision = '6f5c16021161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_validity_date', sa.Date(), nullable=True))

    with op.batch_alter_table('work_schedules', schema=None) as batch_op:
        batch_op.drop_column('exception_type')
        batch_op.drop_column('exception_date')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('exception_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('exception_type', sa.VARCHAR(length=12), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('schedule_validity_date')

    # ### end Alembic commands ###
