"""add guardian fields to patient model

Revision ID: af52122077e3
Revises: bf039c95e71e
Create Date: 2025-07-01 13:28:04.586280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af52122077e3'
down_revision = 'bf039c95e71e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guardian_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('guardian_dni', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('guardian_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('guardian_relationship', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('guardian_relationship')
        batch_op.drop_column('guardian_phone')
        batch_op.drop_column('guardian_dni')
        batch_op.drop_column('guardian_name')

    # ### end Alembic commands ###
